---
title: "loops_and_functions.Rmd"
author: "Juliet"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(palmerpenguins)
```

# task 1

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

transects <- c("Transect A", "Transect B", "Transect C")

week_trans_matrix <- matrix(ncol = length(transects), nrow = length(weekdays))

for (i in seq_along(transects)) {
  for (j in seq_along(weekdays)) {
    week_trans_matrix[j, i] <- paste(weekdays[i], "-",  transects[j])
  }
}

week_trans_matrix

```

# task 2

```{r}

force <- function(mass, a) {

force_N <- mass * a

return(paste("The resulting force is", force_N, "Newtons"))
       
       }

force(mass = 10, a = 2)




#paste("The resulting force is", force_N, "Newtons")
```

#task 3

```{r}
name_column <- function(df, col_num) {
  
  if (col_num < 1) {
    stop("column number must be > 1")
  }
  
  if (col_num > ncol(df)) {
    stop("dataframe doesn't have that many columns")
  }
  
  for (i in 1:ncol(df)) {
    col_name <- colnames(df[i])
    return(col_name)
  }
}

name_column(df = mtcars, col_num = 2)

```

# task 4

```{r}

  gw_depth_slope <- data.frame(sitename = c("mountain", "prairie", "beach", "desert"),
                               depth = c(32, 41, 63, 2),
                               slope = c(11.2, 0.4, 0.8, 2.6))
                               
  site_select <- dplyr::filter(gw_depth_slope, sitename == site)
  
  transport_rate <- 1.4 * site_select$slope + 3.6 * site_select$depth
  
  return(transport_rate)
}

# alternative for site_select line in the gw_rate function:   gw_depth_slope %>% filter(sitename == site)

gw_rate(site = "beach")


#----------------------------------------


fish_parms <- data.frame(sci_name = c("Chanos chanos", "Sphyaena barracuda", "Caranx ignobilis"),
                         common_name = c("milkfish", "great barracuda", "giant trevally"),
                         a_est = c(0.0905, 0.0181, 0.0353),
                         b_est = c(2.52,3.27, 3.05))

fish_weight <- function(fish_name, tot_length) {
   
  fish_select <- dplyr::filter(fish_parms, common_name == fish_name)
  
  weight <- (fish_select$a_est) * (tot_length^(fish_select$b_est))
  
  return(weight)
}

fish_weight(fish_name = "milkfish", tot_length = 5)


fish_parms

#--------------------------

weights_vec <- seq(from = 0, to = 100, by = 1)

milkfish_weights <- fish_weight(fish_name = "milkfish", tot_length = weights_vec)

milkfish_weights

```

# task 5

```{r}
wave_power <- function(wave_height, period) {
  power <- 0.5*(wave_height^2)*period
  return(power)
}

wave_range <- seq(from = 0, to = 3, by = 0.2)

wave_power(wave_height = wave_range, period = 8)

```

# task 6

```{r}

wave_power_either <- function(water_depth, wave_height, period) {
  
  if (water_depth > 12) {
    return(power)
    message("used the deep equation")
  }
  
  if (water_depth <= 12) {
    power_shallow <- 0.81 * wave_height^period
    return(power_shallow)
    message("used the shallow equation")
  }
  
}

wave_power_either(water_depth = 10, wave_height = 1, period = 8)



```































